### ISSUE TITLE
Application to named parameters

### ISSUE THREAD

**Issue by Andersmholmgren** [chalin/DEP-non-null#9] opened 2015-05-26 05:05 UTC
This is a copy of https://github.com/gbracha/nullAwareOperators/issues/12

It wasn't clear to me how this case is handled in this spec either.

Currently named parameters with default values often become useless as explicitly passing null stops the default occurring.

For example

```
foo({String blah: 'blah'});

bar({String blah}) => foo(blah: blah);
```

If blah is null into bar then it will pass that to foo and the  default value not used

So in practice you end up needing to do 

```
foo({String blah}) {
  if (blah == null)  blah = 'blah'
}
```

This seems to happen so often as to almost render defaults on named parameters fairly useless.

Does this proposal provide any help for this case? 

Does it need extra sugar? Dare I suggest

```
foo(blah ?: possiblyNullValue);
```

where the semantics are if possiblyNullValue is null then don't set the named parameter blah to method foo (leave it to default)

**Comment by chalin** [comment] 2015-05-28 21:21
> Currently named parameters with default values often become useless as explicitly passing null stops the default occurring. ...
> 
> ``` dart
> foo({String blah: 'blah'});
> ```
> 
> This seems to happen so often as to almost render defaults on named parameters fairly useless.
> Does this proposal provide any help for this case?

Yes, in that a call like `foo(null)` where `foo()` is as declared above, would result in a static warning and a dynamic type error, since the `blah` optional parameter is declared as a non-null `String`.

**Comment by Andersmholmgren** [comment] 2015-05-28 23:00
To me the fundamental problem here is that

```
foo(blah:null);
```

is treated differently to

```
foo();
```

which in my experience is not what you want. I was hoping that there was someway to remedy that within this proposal

**Comment by chalin** [comment] 2015-05-28 23:27
It is treated differently _by design_: `null` is the _default_ **value** assigned to an optional parameter when no corresponding argument is provided at a point of call. If you change the default value to `'blah'` then there is no other special processing done when a `null` argument is provided (`null` is a possible legal argument value; it doesn't always mean "no argument was provided").

If your objection is to the need to have the `if (blah == null) blah = 'blah';` statement then this proposal allows you to exclude `null` as a permitted value (in checked mode) for the argument `blah`. Which will allow you to drop the conditional statement.

**Comment by Andersmholmgren** [comment] 2015-05-29 21:56
Yeah that makes total sense. Unfortunately it still leaves the defaulting to be cumbersome in many cases.

Consider the case of named parameters in constructors

```
class A {
  A({String foo: 'foo'});
}

class B extends A {
  B({String foo}) : super(foo:foo);
}

```

B either needs to repeat the defaulting for foo or it may end up passing null value for foo to the A constructor. 

I realise that the defaulting of the parameters is part of the contract of the constructors and methods, so in this sense the defaulting should be repeated. However, this does end up a pain keeping them all in sync.

So it would be nice if there was a way to express that I only want to pass the value for the named parameter to the A constructor if B was given a value for it.

That's what I was getting at with my poor attempt at language design by adding the '?:' notation. Like in

```
class B extends A {
  B({?String foo}) : super(foo?:foo);
}

```

So if the caller did

```
new B();
```

then this would be treated as calling the A construction with no value for foo. i.e. like 

```
super();
```

But if the caller did

```
new B(foo: 'fred');
```

then this would be treated as calling the A construction with a value of 'fred' for foo. i.e. like 

```
super(foo: foo);
```

**Comment by chalin** [comment] 2015-05-30 00:10
Ah thanks, for clarifying your intent. That seems like a legitimate use case to me. But it would best be served by its own DEP / feature request on, say, "_null-aware optional named parameter syntax_" (kin to the [Null-aware operators DEP](https://github.com/gbracha/nullAwareOperators)), or maybe it could be treated as part of the [Full optional parameters DEP](https://github.com/lrhn/dep-optionals). 

I can understand the need to be [DRY](http://en.wikipedia.org/wiki/Don't_repeat_yourself). Until there is a language feature in support of your use case, maybe this could be an acceptable approach for you?

``` dart
class A {
  static const String FOO_DEFAULT = 'foo';
  A({String foo: FOO_DEFAULT});
}

class B extends A {
  B({String foo: A.FOO_DEFAULT}) : super(foo: foo);
}
```

I encourage you to pursue this as a feature request, but since it isn't core to non-null types, I'll close this issue.

**Closed as completed by chalin** 2015-05-30 00:10 UTC
